### ISSUE TITLE
Add rule: length-zero-no-unit

### ISSUE THREAD

**Issue by cmslewis** [palantir/stylelint-config-palantir#17]
Could we add stylelint's [`length-zero-no-unit`](https://stylelint.io/user-guide/rules/length-zero-no-unit/) rule? Units are just cruft on `0` values in CSS.

i.e.

**Disallow**
```scss
a { margin-top: 0px; }
```

**Allow**
```scss
a { margin-top: 0; }
```

See the link above for all the nuance.
